// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClmUGY8KgcAyNMaU4Rfn59XeF-bkAr2SU',
    appId: '1:867534025154:web:bb8489ff5e7d035bdda65b',
    messagingSenderId: '867534025154',
    projectId: 'chitchat-25129',
    authDomain: 'chitchat-25129.firebaseapp.com',
    storageBucket: 'chitchat-25129.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjpf1DAsXR7AFjbOgdtBM3i4-huvYGet4',
    appId: '1:867534025154:android:cf2b86ac3d2dbefadda65b',
    messagingSenderId: '867534025154',
    projectId: 'chitchat-25129',
    storageBucket: 'chitchat-25129.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBURdMXxXbQXIrZzBWNk491VmjMem9Lf-k',
    appId: '1:867534025154:ios:f06bf9022f6089f6dda65b',
    messagingSenderId: '867534025154',
    projectId: 'chitchat-25129',
    storageBucket: 'chitchat-25129.appspot.com',
    iosBundleId: 'com.example.chitchat',
  );
}
